version: '3.8'

services:
  # Container da API Laravel
  app:
    container_name: api_laravel_lotacao  
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - minio
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_KEY=minioadmin
      - MINIO_SECRET=minioadmin
      - MINIO_BUCKET=laravel

  # Container do PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Container do MinIO
  minio:
    image: minio/minio
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

# Volumes para persistência de dados
volumes:
  postgres_data:
  minio_data:
